development:
  adapter: postgresql
  encoding: UTF-8
  database: prediciendo
  host: localhost
  pool: 5
  username: thealarmfactory
  password: 1p4rp3ad
  port: 5432

test:
  adapter: postgresql
  encoding: UTF-8
  database: prediciendo_test
  pool: 5
  host: localhost
  username: thealarmfactory
  password: 1p4rp3ad
  port: 5432

production:
  adapter: postgresql
  encoding: UTF-8
  database: prediciendo
  pool: 5
  host: localhost
  username: thealarmfactory
  password: 1p4rp3ad
  port: 5432
