development:
  adapter: postgresql
  encoding: UTF-8
  database: prediciendo
  host: localhost
  pool: 5
  username: ***
  password: ***
  port: 5432

test:
  adapter: postgresql
  encoding: UTF-8
  database: prediciendo_test
  pool: 5
  host: localhost
  username: ***
  password: ***
  port: 5432

production:
  adapter: postgresql
  encoding: UTF-8
  database: prediciendo
  pool: 5
  host: localhost
  username: ***
  password: ***
  port: 5432
